export declare const cwd: any;
export declare const chdir: any;
export declare const getuid: any;
export declare const nextTick: any;
export declare const kill: any;
export declare const env: any;
export declare function exit(code: number): void;
export declare const argv: any;
export declare const argv0: any;
export declare const execPath: any;
export declare const arch: any;
export declare const platform: any;
export declare const pid: any;
export declare const ppid: any;
export declare const execArgv: never[];
declare const _default: {
    cwd: any;
    exit: typeof exit;
    chdir: any;
    getuid: any;
    nextTick: any;
    kill: any;
    env: any;
    arch: any;
    platform: any;
    argv: any;
    argv0: any;
    execArgv: never[];
    execPath: any;
    pid: any;
    ppid: any;
};
export default _default;
